// Code generated by Kitex v0.6.1. DO NOT EDIT.

package studentservice

import (
	client0 "client/kitex_gen/client"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return studentServiceServiceInfo
}

var studentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "StudentService"
	handlerType := (*client0.StudentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Register": kitex.NewMethodInfo(registerHandler, newStudentServiceRegisterArgs, newStudentServiceRegisterResult, false),
		"Query":    kitex.NewMethodInfo(queryHandler, newStudentServiceQueryArgs, newStudentServiceQueryResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "client",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*client0.StudentServiceRegisterArgs)
	realResult := result.(*client0.StudentServiceRegisterResult)
	success, err := handler.(client0.StudentService).Register(ctx, realArg.Info)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStudentServiceRegisterArgs() interface{} {
	return client0.NewStudentServiceRegisterArgs()
}

func newStudentServiceRegisterResult() interface{} {
	return client0.NewStudentServiceRegisterResult()
}

func queryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*client0.StudentServiceQueryArgs)
	realResult := result.(*client0.StudentServiceQueryResult)
	success, err := handler.(client0.StudentService).Query(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStudentServiceQueryArgs() interface{} {
	return client0.NewStudentServiceQueryArgs()
}

func newStudentServiceQueryResult() interface{} {
	return client0.NewStudentServiceQueryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, info *client0.Student) (r *client0.RegisterResp, err error) {
	var _args client0.StudentServiceRegisterArgs
	_args.Info = info
	var _result client0.StudentServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Query(ctx context.Context, req *client0.QueryReq) (r *client0.Student, err error) {
	var _args client0.StudentServiceQueryArgs
	_args.Req = req
	var _result client0.StudentServiceQueryResult
	if err = p.c.Call(ctx, "Query", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
